package com.ruozedata.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.Date;

public class AccountHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.OrganId
     *
     * @mbggenerated
     */
    private Long organid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    private Long handspersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    private BigDecimal changeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.TotalPrice
     *
     * @mbggenerated
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.AccountId
     *
     * @mbggenerated
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.BillNo
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.BillTime
     *
     * @mbggenerated
     */
    private Date billtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruozedata_accounthead.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.Id
     *
     * @return the value of ruozedata_accounthead.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.Id
     *
     * @param id the value for ruozedata_accounthead.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.Type
     *
     * @return the value of ruozedata_accounthead.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.Type
     *
     * @param type the value for ruozedata_accounthead.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.OrganId
     *
     * @return the value of ruozedata_accounthead.OrganId
     *
     * @mbggenerated
     */
    public Long getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.OrganId
     *
     * @param organid the value for ruozedata_accounthead.OrganId
     *
     * @mbggenerated
     */
    public void setOrganid(Long organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.HandsPersonId
     *
     * @return the value of ruozedata_accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    public Long getHandspersonid() {
        return handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.HandsPersonId
     *
     * @param handspersonid the value for ruozedata_accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    public void setHandspersonid(Long handspersonid) {
        this.handspersonid = handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.ChangeAmount
     *
     * @return the value of ruozedata_accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.ChangeAmount
     *
     * @param changeamount the value for ruozedata_accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.TotalPrice
     *
     * @return the value of ruozedata_accounthead.TotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.TotalPrice
     *
     * @param totalprice the value for ruozedata_accounthead.TotalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.AccountId
     *
     * @return the value of ruozedata_accounthead.AccountId
     *
     * @mbggenerated
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.AccountId
     *
     * @param accountid the value for ruozedata_accounthead.AccountId
     *
     * @mbggenerated
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.BillNo
     *
     * @return the value of ruozedata_accounthead.BillNo
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.BillNo
     *
     * @param billno the value for ruozedata_accounthead.BillNo
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.BillTime
     *
     * @return the value of ruozedata_accounthead.BillTime
     *
     * @mbggenerated
     */
    public Date getBilltime() {
        return billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.BillTime
     *
     * @param billtime the value for ruozedata_accounthead.BillTime
     *
     * @mbggenerated
     */
    public void setBilltime(Date billtime) {
        this.billtime = billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.Remark
     *
     * @return the value of ruozedata_accounthead.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.Remark
     *
     * @param remark the value for ruozedata_accounthead.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.tenant_id
     *
     * @return the value of ruozedata_accounthead.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.tenant_id
     *
     * @param tenantId the value for ruozedata_accounthead.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruozedata_accounthead.delete_Flag
     *
     * @return the value of ruozedata_accounthead.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruozedata_accounthead.delete_Flag
     *
     * @param deleteFlag the value for ruozedata_accounthead.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}